[package]
name = "callme"
version.workspace = true
edition.workspace = true
repository.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
anyhow.workspace = true
async-channel.workspace = true
audio_thread_priority.workspace = true
bytes.workspace = true
cpal.workspace = true
dasp_sample.workspace = true
derive_more.workspace = true
fixed-resample.workspace = true
iroh.workspace = true
iroh-quinn.workspace = true
iroh-roq.workspace = true
n0-future.workspace = true
opus.workspace = true
rand.workspace = true
rand_core.workspace = true
ringbuf.workspace = true
serde.workspace = true
spin_sleep.workspace = true
tokio = { workspace = true, features = ["sync"] }
tokio-util.workspace = true
tracing.workspace = true
webrtc-audio-processing = { workspace = true, optional = true }
webrtc-media.workspace = true

[target.'cfg(target_family = "wasm")'.dependencies]
cpal = { workspace = true, features = ["wasm-bindgen"] }

[dev-dependencies]
clap.workspace = true
hound.workspace = true
testresult.workspace = true
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }
tracing-subscriber.workspace = true
tracing-test.workspace = true
futures-concurrency.workspace = true

[features]
default = ["audio-processing"]
audio-processing = ["webrtc-audio-processing"]
