[package]
name = "callme-egui"
version.workspace = true
edition.workspace = true
repository.workspace = true
license.workspace = true
authors.workspace = true
description = "make voicecalls over iroh (gui app)"

[lib]
crate-type = ["lib", "cdylib"]

[dependencies]
anyhow.workspace = true
async-channel.workspace = true
egui.workspace = true
iroh.workspace = true
callme.workspace = true
n0-future.workspace = true
tokio = { workspace = true, features = ["rt", "rt-multi-thread", "sync"] }
tracing.workspace = true
tracing-subscriber.workspace = true
strum.workspace = true

[target.'cfg(target_os = "android")'.dependencies]
android_clipboard.workspace = true
tracing-android.workspace = true
eframe = { workspace = true, default-features = false, features = ["wgpu", "android-native-activity", "default_fonts"] }
egui-winit = { workspace = true, default-features = false, features = ["clipboard", "links"] }

[target.'cfg(target_os = "ios")'.dependencies]
eframe = { workspace = true, default-features = false, features = ["accesskit", "default_fonts", "wgpu"] }

[target.'cfg(not(target_os = "android"))'.dependencies]
eframe = { workspace = true, default-features = false, features = ["default_fonts", "accesskit", "x11", "wayland", "glow"] }
arboard.workspace = true

[features]
default = ["audio-processing"]
audio-processing = ["callme/audio-processing"]

[[package.metadata.android.uses_permission]]
name = "android.permission.INTERNET"
[[package.metadata.android.uses_permission]]
name = "android.permission.ACCESS_NETWORK_STATE"
[[package.metadata.android.uses_permission]]
name = "android.permission.CHANGE_NETWORK_STATE"
[[package.metadata.android.uses_permission]]
name = "android.permission.RECORD_AUDIO"

[package.metadata.bundle]
name = "callme"
identifier = "computer.n0.callme"
