[package]
name = "callme-cli"
version.workspace = true
edition.workspace = true
repository.workspace = true
license.workspace = true
authors.workspace = true
description = "make voicecalls over iroh (cli app)"

[package.metadata.wix]
upgrade-guid = "5EE47959-3AF5-4C59-BB50-C27106F2EF0D"
path-guid = "A8E48474-C88A-430F-904A-019A704E797A"
license = false
eula = false

[dependencies]
anyhow.workspace = true
clap.workspace = true
callme.workspace = true
tokio = { workspace = true, features = ["macros", "rt-multi-thread", "rt"] }
tracing.workspace = true
tracing-subscriber.workspace = true
iroh.workspace = true
dialoguer.workspace = true
n0-future.workspace = true

[features]
default = ["audio-processing"]
audio-processing = ["callme/audio-processing"]
